version: '3.8'
services:
    app:
      container_name: app
      build:
          context: docker-app
          dockerfile: dockerfile
      image: app:latest
      ports:
        - 3000:3001
      networks:
        - spring-cloud-network
networks:
  spring-cloud-network:
      driver: bridge